#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
وحدة كشف WAF (Web Application Firewall)
تكتشف إذا كان الموقع محمياً بـ WAF وتحدد نوعه.
"""

import urllib.request
import urllib.error
import ssl
import re


# ==================== إعدادات SSL ====================
SSL_CONTEXT = ssl.create_default_context()
SSL_CONTEXT.check_hostname = False
SSL_CONTEXT.verify_mode = ssl.CERT_NONE


# ==================== أنماط WAF ====================
WAF_SIGNATURES = {
    'Cloudflare': {
        'headers': ['cf-ray', 'cf-cache-status', 'server: cloudflare'],
        'cookies': ['__cfduid', '__cf_bm', 'cf_clearance'],
        'body': ['cloudflare', 'cf-error-details', 'Attention Required']
    },
    'ModSecurity': {
        'headers': ['server: apache', 'x-mod-security'],
        'body': ['ModSecurity', 'Mod_Security', 'This error was generated by Mod_Security']
    },
    'AWS WAF': {
        'headers': ['x-amzn-requestid', 'x-amz-cf-id'],
        'body': ['AWS WAF', 'Request blocked']
    },
    'Akamai': {
        'headers': ['x-akamai-transformed', 'akamai-grn'],
        'body': ['Akamai', 'Reference #']
    },
    'Sucuri': {
        'headers': ['x-sucuri-id', 'x-sucuri-cache'],
        'body': ['Sucuri', 'Access Denied - Sucuri Website Firewall']
    },
    'F5 BIG-IP': {
        'cookies': ['BIGipServer', 'TS01', 'F5_ST'],
        'body': ['F5 Networks', 'Request Rejected']
    },
    'Imperva': {
        'headers': ['x-iinfo'],
        'cookies': ['incap_ses', 'visid_incap'],
        'body': ['Imperva', 'Incapsula']
    },
    'Barracuda': {
        'cookies': ['barra_counter_session'],
        'body': ['Barracuda', 'You have been blocked']
    }
}


# ==================== دوال الكشف ====================
def send_test_request(url, timeout=10, cookies=None):
    """
    إرسال طلب اختباري مع حمولة خبيثة.
    
    الإرجاع:
        dict: يحتوي على:
              - status: كود الحالة.
              - headers: الهيدرات.
              - body: محتوى الرد.
              - blocked: هل تم الحجب؟
    """
    try:
        headers = {
            'User-Agent': "Mozilla/5.0 (XSStrike-Lite Scanner) <script>alert(1)</script>",
            'X-Test': "' OR 1=1--",
        }
        
        if cookies:
            headers['Cookie'] = '; '.join([f"{k}={v}" for k, v in cookies.items()])
        
        # أضف حمولة خبيثة في URL
        test_url = url + ("&" if "?" in url else "?") + "test=<script>alert(1)</script>"
        
        request = urllib.request.Request(test_url, headers=headers)
        
        with urllib.request.urlopen(request, timeout=timeout, context=SSL_CONTEXT) as response:
            body = response.read().decode('utf-8', errors='ignore')
            return {
                'status': response.status,
                'headers': dict(response.headers),
                'body': body,
                'blocked': False
            }
    
    except urllib.error.HTTPError as e:
        # حتى لو رجع خطأ، نحتاج للتحليل
        body = e.read().decode('utf-8', errors='ignore')
        return {
            'status': e.code,
            'headers': dict(e.headers),
            'body': body,
            'blocked': e.code in (403, 406, 419, 429, 501, 503)
        }
    
    except Exception as e:
        return {
            'status': 0,
            'headers': {},
            'body': '',
            'blocked': False,
            'error': str(e)
        }


def detect_waf(url, timeout=10, cookies=None):
    """
    كشف WAF على الموقع المستهدف.
    
    الإرجاع:
        dict: يحتوي على:
              - detected (bool): هل تم كشف WAF؟
              - name (str): اسم WAF.
              - evidence (list): الأدلة.
    """
    result = {
        'detected': False,
        'name': 'غير معروف',
        'evidence': []
    }
    
    # إرسال طلب اختباري
    print("  🔍 إرسال طلب اختباري...")
    response = send_test_request(url, timeout=timeout, cookies=cookies)
    
    if response.get('error'):
        result['evidence'].append(f"خطأ في الاتصال: {response['error']}")
        return result
    
    # تحليل الهيدرات
    headers_lower = {k.lower(): str(v).lower() for k, v in response['headers'].items()}
    body_lower = response['body'].lower()
    
    # البحث في كل WAF معروف
    for waf_name, signatures in WAF_SIGNATURES.items():
        matches = []
        
        # فحص الهيدرات
        for header in signatures.get('headers', []):
            header_lower = header.lower()
            if ':' in header_lower:
                name, value = header_lower.split(':', 1)
                if name in headers_lower and value in headers_lower[name]:
                    matches.append(f"Header: {header}")
            elif header_lower in headers_lower:
                matches.append(f"Header: {header}")
        
        # فحص الكوكيز
        cookies_str = headers_lower.get('set-cookie', '')
        for cookie in signatures.get('cookies', []):
            if cookie.lower() in cookies_str:
                matches.append(f"Cookie: {cookie}")
        
        # فحص المحتوى
        for pattern in signatures.get('body', []):
            if pattern.lower() in body_lower:
                matches.append(f"Body: {pattern}")
        
        if matches:
            result['detected'] = True
            result['name'] = waf_name
            result['evidence'] = matches
            return result
    
    # إذا تم الحجب بدون بصمة معروفة
    if response['blocked']:
        result['detected'] = True
        result['name'] = 'غير معروف (تم الحجب)'
        result['evidence'].append(f"تم حجب الطلب. كود الحالة: {response['status']}")
    
    return result


# ==================== اختبار ====================
if __name__ == "__main__":
    print("🧪 اختبار كاشف WAF...")
    print()
    
    test_urls = [
        "http://localhost/dvwa/vulnerabilities/xss_r/",
        "https://www.google.com",
    ]
    
    for url in test_urls:
        print(f"🔍 فحص: {url}")
        result = detect_waf(url)
        
        if result['detected']:
            print(f"  🚨 WAF مكتشف: {result['name']}")
            for e in result['evidence']:
                print(f"    - {e}")
        else:
            print(f"  ✅ لا يوجد WAF")
        print()